name: XT_NET_WEB_CI

on: [push, pull_request]

jobs:
  restore:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core text
        run: echo Setup .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      - name: Restore app
        run: |
          cd RD_XT_NET_WEB_CI
          ls -f
          dotnet restore
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build app text
        run: echo Build step was started
      - name: Build app
        run: #|
          ls -f
          # cd RD_XT_NET_WEB_CI
          # ls -f
          # dotnet build --configuration Release
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Step Name
        run: echo Build job